sudo: true
language: node_js
services:
  - mongodb
before_install:
  - npm update -g npm
node_js:
  - '0.10'
branches:
   only:
     - master
notifications:
  email: false
git:
  depth: 1
script: npm test